export const GET_NETWORKS_SAGA = '@@NETWORK/GET_NETWORKS_SAGA';
export const SET_NETWORKS = '@@NETWORK/SET_NETWORKS';
export const SELECT_NETWORK_SAGA = '@@NETWORK/SELECT_NETWORK';
export const SET_CURRENT_NETWORK_ID = '@@NETWORK/SET_CURRENT_NETWORK_ID';
export const REMEMBER_NETWORK = '@@NETWORK/REMEMBER_NETWORK';
